### ISSUE TITLE
Create ARM64 flavor of PostgreSQL image

### ISSUE THREAD

**Issue by KurtStam** [Project31/rh-middleware-on-arm#6]
https://github.com/sclorg/postgresql-container - this needs to support a centos7 arm64 build.

**Comment by zregvart** [comment]
So I managed to build base `s2i-centos` image from https://github.com/sclorg/s2i-base-container.

There's a PR to help with that upstream (https://github.com/sclorg/container-common-scripts/pull/115) and here https://github.com/Project31/container-common-scripts/pull/1.

Steps needed (once https://github.com/Project31/s2i-base-container/pull/1, https://github.com/Project31/s2i-base-container/pull/2 and https://github.com/Project31/container-common-scripts/pull/1 are merged):
```sh
$ git clone https://github.com/Project31/s2i-base-container.git
$ (cd s2i-base-container && make build VERSIONS=core ARCH=arm64v8)
...
s2i core => f36116fa9d73
make[1]: Leaving directory '/home/zregvart/tmp/s2i-base-container'
$ docker images
REPOSITORY                                                TAG                 IMAGE ID            CREATED             SIZE
centos/s2i-core-centos7                                   1                   f36116fa9d73        35 seconds ago      265MB
centos/s2i-core-centos7                                   20190419-571155e    f36116fa9d73        35 seconds ago      265MB
centos/s2i-core-centos7                                   latest              f36116fa9d73        35 seconds ago      265MB
centos/s2i-core-centos7                                   raw                 f36116fa9d73        35 seconds ago      265MB
$ docker run --rm -it f36116fa9d73 uname -a
Linux 55217487c694 5.0.7-200.fc29.x86_64 #1 SMP Mon Apr 8 15:40:59 UTC 2019 aarch64 aarch64 aarch64 GNU/Linux
```

With those changes the build of the PostgreSQL image fails as there is no `centos-release-scl` repository with `aarch64` RPMs. Part of the image creation is trying to install NSS (`nss_wrapper`) PostgreSQL related packages from that repository (`rh-postgresql95`, `rh-postgresql95-postgresql-contrib` and `rh-postgresql94-postgresql-server`), see https://github.com/sclorg/postgresql-container/blob/c5b350a24af4181f3dd3b63e46ed6d65c6b54ae7/specs/multispec.yml#L15.

To test do (once those PRs are merged and `centos/s2i-core-centos7` is build with `ARCH=arm64v8`):
```sh
$ https://github.com/sclorg/postgresql-container.git
$ cd postgresql-container
$ git config -f .gitmodules submodule.common.url https://github.com/Project31/container-common-scripts.git
$ git submodule update --init --recursive --remote
$ make build TARGET=centos7 VERSIONS=9.5
...
package nss_wrapper is not installed
package rh-postgresql95 is not installed
package rh-postgresql95-postgresql-contrib is not installed
package rh-postgresql94-postgresql-server is not installed
The command '/bin/sh -c yum install -y centos-release-scl-rh &&     INSTALL_PKGS="rsync tar gettext bind-utils nss_wrapper rh-postgresql95 rh-postgresql95-postgresql-contrib rh-postgresql94-postgresql-server" &&     yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS &&     rpm -V $INSTALL_PKGS &&     yum clean all &&     localedef -f UTF-8 -i en_US en_US.UTF-8 &&     test "$(id postgres)" = "uid=26(postgres) gid=26(postgres) groups=26(postgres)" &&     mkdir -p /var/lib/pgsql/data &&     /usr/libexec/fix-permissions /var/lib/pgsql &&     /usr/libexec/fix-permissions /var/run/postgresql' returned a non-zero code: 4
make[1]: *** [common/common.mk:80: 9.5] Error 4
make[1]: Leaving directory '/home/zregvart/tmp/postgresql-container'
make: *** [common/common.mk:69: build-serial] Error 2
```

When trying to install one of those packages in the aarch64 container:
```sh
$ yum -y --setopt=tsflags=nodocs install $INSTALL_PKGS
Loaded plugins: fastestmirror, ovl
Loading mirror speeds from cached hostfile


 One of the configured repositories failed (Unknown),
 and yum doesn't have enough cached data to continue. At this point the only
 safe thing yum can do is fail. There are a few ways to work "fix" this:

     1. Contact the upstream for the repository and get them to fix the problem.

     2. Reconfigure the baseurl/etc. for the repository, to point to a working
        upstream. This is most often useful if you are using a newer
        distribution release than is supported by the repository (and the
        packages for the previous distribution release still work).

     3. Run the command with the repository temporarily disabled
            yum --disablerepo=<repoid> ...

     4. Disable the repository permanently, so yum won't use it by default. Yum
        will then just ignore the repository until you permanently enable it
        again or use --enablerepo for temporary usage:

            yum-config-manager --disable <repoid>
        or
            subscription-manager repos --disable=<repoid>

     5. Configure the failing repository to be skipped, if it is unavailable.
        Note that yum will try to contact the repo. when it runs most commands,
        so will have to try and fail each time (and thus. yum will be be much
        slower). If it is a very temporary problem though, this is often a nice
        compromise:

            yum-config-manager --save --setopt=<repoid>.skip_if_unavailable=true

Cannot find a valid baseurl for repo: centos-sclo-sclo/aarch64
```

**Comment by KurtStam** [comment]
I think we should be able to build from the src rpms: http://vault.centos.org/centos/7/sclo/Source/rh/

https://blog.packagecloud.io/eng/2015/04/20/working-with-source-rpms/
http://mirror.centos.org/centos/7/sclo/x86_64/rh/rh-postgresql95/

I was able to create the rh-postgresql95-2.2-2.el7.aarch64.rpm, however there does not seem to be src.rpms for the other missing rpms.

**Comment by KurtStam** [comment]
@zregvart I managed to get all the rpms build from src.rpms. So we should be able to use these and work around the issue.

**Comment by KurtStam** [comment]
I was able to build it on AWS instance `postgres-build`, and pushed it to:
https://hub.docker.com/r/p31arm64v8/postgresql-95-centos7

I preinstalled the rpms that it was missing above and pushed this image up to
https://hub.docker.com/r/kurtstam/slorg-s2i-core-centos 
https://hub.docker.com/r/kurtstam/slorg-pg-build-image (what I used for building)
So you will need to tag this as centos/s2i-core-centos7 on the machine where you are trying to build.
the rpms can be found here for now: https://github.com/Project31/rh-middleware-on-arm

**Comment by KurtStam** [comment]
I think what's next on this: docker.io/wrouesnel/postgres_exporter

**Comment by zregvart** [comment]
That’s awesome, the exporter is only for metrics, we could skip it in this use case...

--

**Comment by KurtStam** [comment]
working!
